### ISSUE TITLE
[influxdb-enterprise] Add support for aggregating custom certs

### ISSUE THREAD

**Issue by chobbs** [influxdata/helm-charts#131]
Add option to allow aggregating custom CA cert on top of all the public certs vs letting custom CA cert overriding public certs (so only those trusted by custom CA is allowed)

**Comment by rawkode** [comment]
Sorry, I don't understand what's being asked here.

What problem did the customer have?

**Comment by blai** [comment]
Let me try to explain. It may have to do with how I got passed the issue. For context sake, we have configured custom signed TLS certs and enabled HTTPS. Forgot the detail, but we hit some issue with TLS validation and saw the error in the log complaining missing CA cert in a specific path at `/var/run/secrets/tls/` (I hope I got this right), so I added logic in statefulset to mount our CA cert to that path, and TLS validation started working. But noticed that when I mount the CA cert this way, it seems all traffics to URLs using publicly signed certs are not having issue. The ask here is to provide support for custom CA cert in a way that it doesn't break the public cert validation.

**Comment by rawkode** [comment]
@blai When using self-signed certificates, you should enable the `insecure` parameter in the chart; which will remove errors.

If there are still errors from this, then that may be a bug elsewhere.

You should not overwrite the CA provided to the containers if they're also to receive public routed traffic.

Can you confirm if you tried insecure with your self signed certificates and still received errors, please?

**Comment by timhallinflux** [comment]
Option 1: use license keys -- which contacts the license server and attempts to validate that the key being used is still valid and the configuration of the cluster is consistent with the details (node count and processor count).  In this mode, you would use a trusted CA to allow for publicly routed traffic.

Option 2: use license files -- which captures the license details locally and avoids the need to communicate with the license server over the public Internet.  In this mode, you can use self-signed certs and enable the `insecure` parameter. This doesn't mean that TLS is disabled...it is simply a mode to allow for the self-signed cert to be used (`untrusted` is probably a better term which describes the use of the self-signed cert).

**Comment by blai** [comment]
@rawkode `insecure` is no longer an option, although I remember it worked. `insecure` turn off cert validation, and according to our compliance team, cert validation is required.

**Comment by timhallinflux** [comment]
@blai -- I don't understand what the requirement is.  You'll need to define "validation" for me.  

I believe cert verification is what is turned off.  This simply means that the traffic is encrypted between the nodes, but the verification of the cert itself back to a trusted CA is not performed (because you self-signed the cert....there isn't a trusted CA).  
From the documentation:
https://docs.influxdata.com/enterprise_influxdb/v1.8/guides/https_setup/

```Self-signed certificates

Self-signed certificates are not signed by a trusted, third-party CA. Unlike CA-signed certificates, self-signed certificates only provide cryptographic security to HTTPS requests. They do not allow clients to verify the identity of the InfluxDB server. With this certificate option, every InfluxDB Enterprise instance requires a unique self-signed certificate. You can generate a self-signed certificate on your own machine.```

So, I believe the inspiration for this came from `curl`.  You can read up on all the gory details here: https://curl.haxx.se/docs/sslcerts.html

However, the point is -- who is responsible for handling the certs that you are generating for those machines?  
How are you handling this with other software that is going through this similar path?  

My assertion is:
a) this is not the responsibility of the Helm Chart to perform cert handling -- it is simply referencing the certs that are supplied by you
b) InfluxDB provides a mechanisms to allow for either approach: verification back to a CA or skipping the verification But the handling of the certs themselves isn't within the scope of either the chart or InfluxDB

**Comment by blai** [comment]
The compliance requirement we got is: all transaction between any server (in Kubernetes, between pods, services, etc) requires end to end encryption using TLS 1.2 or above, all TLS transactions needs to be validated with CA cert (this applies to certificates signed by both public CA certs or private CA certs). With this description, I think the requirement is to support mTLS.
