### ISSUE TITLE
Cannot connect to docker daemon.

### ISSUE THREAD

**Issue by manucloud9** [influxdata/helm-charts#267]
I am trying to install telegraf-ds. The pods are running but I am seeing below error:

2021-02-10T12:43:50Z E! [inputs.docker] Error in plugin: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-02-10T12:44:00Z E! [inputs.docker] Error in plugin: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I am not seeing such an error when I run telegraf helm-chart. It's only with telegraf-ds helm chart. Any suggestions.

**Comment by nsteinmetz** [comment]
Hello @manucloud9 

In which context do you deploy your cluster ? Does it use the docker runtime ?

For ex, GKE plan to drop docker runtime from GKE 1.19 and more globally docker runtime will be dropped with kubernetes 1.20 in favor of containerd.

Afaik, containerd does not provide the docker socket so this error will occur more and more...

I don't know if there is a containerd plugin to get metrics instead of docker ones.

**Comment by nsteinmetz** [comment]
Just checked ; No containerd plugin yet...

**Comment by manucloud9** [comment]
> Hello @manucloud9
> 
> In which context do you deploy your cluster ? Does it use the docker runtime ?
> 
> For ex, GKE plan to drop docker runtime from GKE 1.19 and more globally docker runtime will be dropped with kubernetes 1.20 in favor of containerd.
> 
> Afaik, containerd does not provide the docker socket so this error will occur more and more...
> 
> I don't know if there is a containerd plugin to get metrics instead of docker ones.

Yes, I am using docker runtime

**Comment by nsteinmetz** [comment]
Which version of oss k8S ? on bare metal ? vms ?

**Comment by lukonjun** [comment]
Hi there, i am facing the same issue. I have k3s installed with containerd on ubuntu 20.04 VMs. 
`kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}`
Is there any way to use telegraf or do i need to switch to docker runtime?

**Comment by nsteinmetz** [comment]
With containerd, there is no more docker socket (aka `/var/run/docker.sock`)- so metrics can no longer be retrieved from this endpoint. I don't know if there is an alternative.

**Comment by lukonjun** [comment]
Alright thanks, as a workaround i set up my k3s cluster newly up with docker instead of containerd as the container runtime

**Comment by tobittc** [comment]
We are currently trying to use the telegraf-ds in GKE and are getting the same issue. 
Could the [[input.docker]] section be made configurable instead of being hard coded in the configmap? 
Have been trying to find a way to remove that section using kustomize, but have failed so far. (if anyone has any suggestions how to do this that would also be great).
