### ISSUE TITLE
[telegraf-ds] Use serviceAccountName in ClusterRole

### ISSUE THREAD

**Issue by dougsc** [influxdata/helm-charts#323]
If I try and use an existing service account for the `telegraf-ds` chart - ie.,

```
  serviceAccount:
    create: false
    name: my-sa
```

The resulting `ClusterRoleBinding` seems to end up with the incorrect SA name - eg,

```
  - kind: ServiceAccount
    name: <value of telegraf.fullname>
```

I tested this diff and it seemed to correct the SA name:

```diff
--- a/charts/telegraf-ds/templates/rolebinding.yaml
+++ b/charts/telegraf-ds/templates/rolebinding.yaml
@@ -7,10 +7,10 @@ metadata:
     {{- include "telegraf.labels" . | nindent 4 }}
 subjects:
   - kind: ServiceAccount
-    name: {{ include "telegraf.fullname" . }}
+    name: {{ include "telegraf.serviceAccountName" . }}
     namespace: {{ .Release.Namespace }}
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
```

It also stopped these errors reported by telegraf (associated with the binding not being applied):

```
E! [inputs.kubernetes] Error in plugin: https://nn.nn.nn.nn:10250/stats/summary returned HTTP status 403 Forbidden
```

If you think this is a valid issue and agree with the fix I'd be happy to make a PR for it.

Thanks

**Comment by alespour** [comment]
Apologies for the delayed response. It is a valid issue, all 3 telegraf charts are affected

```
charts/telegraf/templates/rolebinding.yaml
charts/telegraf-ds/templates/rolebinding.yaml
charts/telegraf-operator/templates/clusterrolebinding.yml
```

Would you still be willing to make a PR? Thank you.

**Comment by dougsc** [comment]
Sure, I'll create a PR this week

**Comment by wojciechka** [comment]
@dougsc @alespour I had some time and checked `telegraf-operator` chart in context of this issue and #440.

This is because `telegraf-operator` works differently - it needs to be able to manipulate Kubernetes Secrets and it will always need to have a service account.

It will always create service account (and its name is never empty), I don't think anything needs to change in that chart.

So no action needed for `telegraf-operator`.
