### ISSUE TITLE
Telegraf on Kubernetes: Error: Service "telegraf" is invalid: spec.ports: Required value

### ISSUE THREAD

**Issue by chandhukeenz** [influxdata/helm-charts#335]
**what do I want to do?**
I'm trying to deploy telegraf in my Kubernetes cluster so that I can use Telegraf's **Prometheus** input plugin to read the data (metrics) from a particular URL and write the metrics in a file using telegraf's output **file** plugin.
**what did I do?**
I used the telegraf [helm chart](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf) to deploy telegraf on kubernetes. I changed the following config changes.
**The original telegraf yaml file:**
![image](https://user-images.githubusercontent.com/55447161/123103336-85607f80-d453-11eb-8649-40ca26dc86ce.png)
**The changes I made to it:**
![image](https://user-images.githubusercontent.com/55447161/123103104-521df080-d453-11eb-9f7f-5476d25fc935.png)
And when I applied the helm chart along with the changes I got 
**Error: Service "telegraf" is invalid: spec.ports: Required value** and my deployment failed.
![image](https://user-images.githubusercontent.com/55447161/123103675-dec8ae80-d453-11eb-86d0-ad89da09d1c8.png)
Please do help me if I'm making any mistakes on the changed YAML configuration since I didn't find any resource for yaml format of telegraf's input and output plugin.
Additional link for reference: 
[telegraf .conf file](https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf)

**Comment by sidju** [comment]
I have also run into this issue. From my debugging the problem seems to be that the spec.ports heading is created in the [service.yaml](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/templates/service.yaml) file no matter if there are any ports opened.

I took a quick look into fixing this, but the best solution I can think of would require a variable to track if the spec.ports heading has been added, adding it before items needing it if it hasn't. I don't know if helm supports this nor how easy it would be, so I'll hold off on it for now.

**Comment by sidju** [comment]
Also, for those just wanting a quick fix:
If you set true to metrics.health.enabled in your values it will open port 8888 and resolve this issue with minimal influence on the application.

**Comment by nward** [comment]
A better solution is to set `service.enabled: false` - if you're not going to set ports you don't need the service.

**Comment by alespour** [comment]
Without any configure listener, there's no need to use the service. By setting `service.enabled: false` it can be skipped altogether then, thanks @nward.
