### ISSUE TITLE
[Bug] Broken InfluxDB chart compatibility with Kubernetes 1.22 after 4.10.2 release

### ISSUE THREAD

**Issue by vzabawski** [influxdata/helm-charts#466]
I have a vanilla Kubernetes 1.22.4 cluster with InfluxDB installed with Helm chart.
Version 4.10.1 works perfectly, while versions 4.10.2 and later generate Ingress resource incompatible with my Kubernetes cluster.
The problem lays in changes in API version checking mechanics introduced with this commit: https://github.com/influxdata/helm-charts/commit/e62e767e39e477fb78d0a5066ec8031924691836
My Kubernetes cluster doesn't have `networking.k8s.io/v1/Ingress`, only `networking.k8s.io/v1`, so `.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"` returns `false` and apiVersion is set to `networking.k8s.io/v1beta1` which is incompatible with k8s 1.22.
Not sure what was the purpose of the change, but if checking for `networking.k8s.io/v1/Ingress` is necessary, I can create a pull request with updated code which checks both versions: `networking.k8s.io/v1/Ingress` and `networking.k8s.io/v1`.

**Comment by alespour** [comment]
I believe the reason for the changes were that is some k8s version, `networking.k8s.io/v1` was available but `Ingress` resource was not. Therefore the check was changed from API version to resource availability check.

So when you try to `helm install` the package with ingress enabled, it fails because Ingress resource def is in generated in `networking.k8s.io/v1beta1` namespace?

**Comment by vzabawski** [comment]
Yes, it generates ingress with `networking.k8s.io/v1beta1`, which was completely removed in k8s 1.22, so I can't deploy the chart.
I guess the best solution in this case is to check for both `networking.k8s.io/v1/Ingress` and `networking.k8s.io/v1` using `or`.

**Comment by alespour** [comment]
What's the output of `kubectl api-resources -o wide | grep ingresses` in your cluster?

**Comment by alespour** [comment]
It is the same as in my testing cluster. Helm resource check for `networking.k8s.io/v1/Ingress` should return true... :thinking: 

I'm using helm 3.7.1. `helm template` renders Ingres in `networking.k8s.io/v1beta` because it uses some compiled-in versions, but `helm install` uses versions from k8s server ie. correctly `networking.k8s.io/v1`.

Could you check the ingress template output of `helm install --set ingress.enabled=true --dry-run --debug  influxdb charts/influxdb`, please?

**Comment by vzabawski** [comment]
You are right. I checked more carefully. I used Helm as a part of CI/CD pipeline and the installation itself work, it's a previous validation step which fails, so I wasn't correct from the beginning about Helm install not working. Sorry for taking your time.
